spring:
  application:
    name: newcracker

  profiles:
    active:
      - test
      - redis

naver:
  api:
    client-id: ndx30wWbAtZkoGPAefNB
    client-secret: taWJjYTm4p
    news-url: https://openapi.naver.com/v1/search/news.json
